async function clearCompletedToday(){
  if(!confirm('Clear all COMPLETED pick lists for today from the active Pick List screen?\n\nStock will NOT be deducted again. History is kept.'))return;
  const {data,error}=await sb.rpc('clear_completed_today');
  if(error)return alert(error.message);
  alert(`${data||0} completed pick list${Number(data)===1?'':'s'} cleared from today’s active view.`);
  await showPickLists();
}
async function printRecipe(id){
  const batches=Math.max(1,parseInt($('recipe_batches_'+id)?.value||'1'));
  const {data:r,error}=await sb.from('recipes').select('code,name,description,base_servings,recipe_ingredients(display_amount,stock_qty_per_batch,sort_order,products(name,unit))').eq('id',id).single();
  if(error)return alert(error.message);
  const lines=(r.recipe_ingredients||[]).sort((a,b)=>a.sort_order-b.sort_order);
  const w=window.open('','_blank','width=800,height=900');
  if(!w)return alert('Allow pop-ups to print the recipe.');
  w.document.write(`<html><head><title>${esc(r.name)}</title><style>body{font-family:Arial;padding:30px;color:#111}h1{margin-bottom:4px}.muted{color:#666}.line{padding:10px 0;border-bottom:1px solid #ccc}.qty{font-weight:bold}@media print{button{display:none}}</style></head><body><button onclick="print()">PRINT</button><h1>${esc(r.name)}</h1><div class="muted">${esc(r.code||'')} · ${batches} batch${batches===1?'':'es'} · ${Number(r.base_servings||0)*batches} portions · ${new Date().toLocaleDateString()}</div><p>${esc(r.description||'')}</p><h2>Ingredients</h2>${lines.map(x=>`<div class="line"><b>${esc(x.products?.name||'Ingredient')}</b><br><span class="qty">${batches===1?esc(x.display_amount):esc(batches+' × '+x.display_amount)}</span><br><span class="muted">Stock units: ${Number(x.stock_qty_per_batch||0)*batches} ${esc(x.products?.unit||'')}</span></div>`).join('')}</body></html>`);
  w.document.close();
}
async function printBatchLabel(batchId,code,name,batchNo,expiry){
  if(profile?.role!=='manager')return alert('Manager access required.');
  const url=location.origin+location.pathname+'?batch='+encodeURIComponent(batchId);
  const holder=document.createElement('div');holder.style.position='fixed';holder.style.left='-9999px';document.body.appendChild(holder);
  new QRCode(holder,{text:url,width:450,height:450});await new Promise(r=>setTimeout(r,80));
  const canvas=holder.querySelector('canvas');const qr=canvas.toDataURL('image/png');holder.remove();
  const w=window.open('','_blank','width=650,height=850');if(!w)return alert('Allow pop-ups to print batch QR labels.');
  w.document.write(`<html><head><title>${esc(code)} ${esc(batchNo)}</title><style>body{font-family:Arial;text-align:center;padding:24px}.code{font-size:34px;font-weight:800}.name{font-size:24px;font-weight:700}.batch{font-size:28px;font-weight:800}.note{font-size:18px}@media print{button{display:none}}</style></head><body><button onclick="print()">PRINT</button><br><img src="${qr}" style="width:360px"><div class="code">${esc(code)}</div><div class="name">${esc(name)}</div><div class="batch">BATCH: ${esc(batchNo)}</div><div class="note">Expiry: ${esc(expiry)}</div><div class="note"><b>SCAN THIS QR BEFORE PICKING</b><br>FIFO / FEFO rotation is checked by the system.</div></body></html>`);
  w.document.close();
}
async function showHistory(setView=true){if(setView)currentView='history';let q=sb.from('stock_transactions').select('*,products(name,scan_code),batches(batch_no,expiry_date)').order('created_at',{ascending:false}).limit(100);const {data,error}=await q;if(error)return alert(error.message);$('content').innerHTML='<div class="card"><h2>'+ (profile.role==='manager'?'Stock History':'My Stock History') +'</h2>'+((data||[]).map(t=>`<p><b>${esc(t.action)}</b> ${t.quantity} — ${esc(t.products?.name||'')} (${esc(t.products?.scan_code||'')})<br><span class="muted">Batch ${esc(t.batches?.batch_no||'')} · ${new Date(t.created_at).toLocaleString()} · ${esc(t.note||'')}</span></p>`).join('')||'No history yet.')+'</div>'}
async function showReceive(setView=true){if(setView)currentView='receive';if(profile.role!=='manager')return;const products=await getProducts();$('content').innerHTML=`<div class="card"><h2>Stock In</h2><label>Product</label><select id="rProduct">${products.map(p=>`<option value="${esc(p.scan_code)}">${esc(p.scan_code)} — ${esc(p.name)}</option>`).join('')}</select><div class="grid"><div><label>Batch / Lot</label><input id="rBatch"></div><div><label>Expiry date</label><input id="rExpiry" type="date"></div><div><label>Quantity</label><input id="rQty" type="number" min="1" value="1"></div><div><label>Supplier</label><input id="rSupplier"></div></div><button id="receiveSave" class="primary" style="margin-top:10px">RECEIVE STOCK</button></div>`;$('receiveSave').onclick=receiveStock}
async function receiveStock(){const {error}=await sb.rpc('receive_stock',{p_scan_code:$('rProduct').value,p_batch_no:$('rBatch').value.trim(),p_expiry_date:$('rExpiry').value,p_quantity:parseInt($('rQty').value||'1'),p_supplier:$('rSupplier').value.trim()||null,p_note:'Stock received via manager screen'});if(error)return alert(error.message);alert('Stock received.');showReceive()}
async function requestConcession(batchId,name,batchNo,maxQty){if(profile?.role!=='manager')return alert('Manager access required.');const n=parseInt(prompt(`Quantity to place on QA concession for ${name} / batch ${batchNo}:`,'1')||'0');if(!n)return;if(n<1||n>Number(maxQty))return alert('Quantity must be between 1 and '+maxQty+'.');const reason=(prompt('Reason for QA review (e.g. damaged pack, temperature issue, out of date, label damage):','')||'').trim();if(!reason)return alert('A reason is required.');const {data,error}=await sb.rpc('create_concession_request',{p_batch_id:batchId,p_quantity:n,p_reason:reason});if(error)return alert(error.message);alert(`Concession CON-${String(data).padStart(6,'0')} created.\n\nNO STOCK HAS BEEN WRITTEN OFF.\nQA must decide USE or THROW AWAY.`);await showConcessions()}
function concessionNo(id){return 'CON-'+String(id).padStart(6,'0')}
async function showConcessions(setView=true){if(setView)currentView='concessions';if(!['manager','qa_manager','qa'].includes(profile?.role))return alert('Manager, QA Manager or QA access required.');const {data,error}=await sb.from('concessions').select('*,products(name,scan_code,unit,container_type,quantity_per_container,container_measure),batches(batch_no,received_date,expiry_date,quantity,supplier),requester:profiles!concessions_requested_by_fkey(display_name),qauser:profiles!concessions_qa_by_fkey(display_name)').order('requested_at',{ascending:false});if(error){const r=await sb.from('concessions').select('*,products(name,scan_code,unit,container_type,quantity_per_container,container_measure),batches(batch_no,received_date,expiry_date,quantity,supplier)').order('requested_at',{ascending:false});if(r.error)return alert(r.error.message);return renderConcessions(r.data||[])}renderConcessions(data||[])}
function renderConcessions(rows){$('content').innerHTML=`<div class="card"><h2>QA Concessions</h2><p class="muted">A Manager can place stock on hold for QA review. Only a QA login can authorise <b>USE UNDER CONCESSION</b> or <b>THROW AWAY</b>.</p></div>`+(rows.length?rows.map(concessionCard).join(''):'<div class="card">No concession requests.</div>')}
function concessionCard(c){const pending=c.status==='PENDING';const statusText=c.status==='APPROVED_USE'?'USE UNDER CONCESSION':c.status==='APPROVED_THROW_AWAY'?'THROW AWAY':'PENDING QA';const statusClass=pending?'warn':c.status==='APPROVED_USE'?'good':'danger';const p=c.products||{},b=c.batches||{};const qaName=c.qauser?.display_name||'';const reqName=c.requester?.display_name||'';const reviewActive=c.review_by&&c.review_started_at&&(Date.now()-new Date(c.review_started_at).getTime())<30*60*1000;const reviewMine=reviewActive&&c.review_by===profile?.user_id;return `<div class="card"><div class="row"><b>${concessionNo(c.id)}</b><span class="pill ${statusClass}">${esc(statusText)}</span></div><h2>${esc(p.name||'Product')}</h2><p class="muted">${esc(p.scan_code||'')} · Batch ${esc(b.batch_no||'')} · Qty on concession: <b>${c.quantity}</b></p><p><b>Reason:</b> ${esc(c.reason)}</p><p class="small muted">Raised: ${new Date(c.requested_at).toLocaleString()}${reqName?' · By '+esc(reqName):''}</p>${c.qa_comment?`<p><b>QA comment:</b> ${esc(c.qa_comment)}</p>`:''}${reviewActive?`<p class="small ${reviewMine?'good':'warn'}"><b>QA review in progress:</b> ${esc(c.review_by_name||'QA')}</p>`:''}${c.decided_at?`<p class="small muted">QA decision: ${new Date(c.decided_at).toLocaleString()}${qaName?' · '+esc(qaName):''}</p>`:''}<div class="row"><button onclick="printConcession(${c.id})">PRINT CONCESSION SHEET</button>${profile?.role==='qa'&&pending&&!reviewActive?`<button onclick="startQaReview(${c.id})">START QA REVIEW</button>`:''}${profile?.role==='qa'&&pending&&reviewMine?`<button class="good" onclick="qaDecision(${c.id},'USE')">QA — ALLOW USE</button><button class="danger" onclick="qaDecision(${c.id},'THROW_AWAY')">QA — THROW AWAY</button><button onclick="releaseQaReview(${c.id})">RELEASE REVIEW</button>`:''}${profile?.role==='qa'&&pending&&reviewActive&&!reviewMine?`<button disabled>UNDER REVIEW BY ${esc(c.review_by_name||'ANOTHER QA')}</button>`:''}</div></div>`}
async function startQaReview(id){const {error}=await sb.rpc('claim_concession_review',{p_concession_id:id});if(error)return alert(error.message);await showConcessions(false)}
async function releaseQaReview(id){const {error}=await sb.rpc('release_concession_review',{p_concession_id:id});if(error)return alert(error.message);await showConcessions(false)}