function pickListCard(pl){
  const items=(pl.pick_list_items||[]).sort((a,b)=>a.sort_order-b.sort_order||a.id-b.id);
  const done=items.filter(x=>x.status==='picked').length;
  const total=items.length;
  const pct=total?Math.round(done*100/total):0;
  return `<div class="card"><div class="row"><b>PICK LIST #${pl.id}</b><span class="pill ${pl.status==='complete'?'good':'warn'}">${esc(pl.status.toUpperCase().replace('_',' '))}</span></div><h2>${esc(pl.recipes?.name||'Recipe')}</h2><p class="muted">${esc(pl.recipes?.code||'')} · ${pl.batches} batch${pl.batches===1?'':'es'} · ${Number(pl.recipes?.base_servings||0)*pl.batches} portions</p><p><b>Progress:</b> ${done}/${total} items picked (${pct}%)</p>${items.map(pickListItemLine).join('')} ${pl.status==='complete'?'<p class="good" style="padding:10px;border-radius:9px"><b>COMPLETE</b> — all ingredients have been picked and deducted from stock.</p>':''}</div>`;
}
function pickListItemLine(item){
  const p=item.products||{};
  const batches=(p.batches||[]).filter(b=>Number(b.quantity)>0&&daysUntil(b.expiry_date)>=0).sort((a,b)=>a.expiry_date.localeCompare(b.expiry_date)||String(a.received_date||'').localeCompare(String(b.received_date||'')));
  const available=batches.reduce((s,b)=>s+Number(b.quantity||0),0);
  const next=batches[0];
  const picked=item.status==='picked';
  const claimActive=item.claimed_by && item.claimed_at && (Date.now()-new Date(item.claimed_at).getTime())<15*60*1000;
  const mine=claimActive && item.claimed_by===profile?.user_id;
  const claimText=claimActive ? `Being handled by ${esc(item.claimed_by_name||'another user')}` : '';
  return `<div class="batch ${picked?'pickedItem':available<item.required_qty?'danger':''}"><div class="pickedText"><div class="row"><div style="flex:1"><b>${esc(p.name||'Ingredient')}</b><br><span class="muted">${esc(p.scan_code||'')} · Location: ${esc(p.location||'Not set')}</span></div><span class="pill ${picked?'good':''}">${picked?'PICKED':'TO PICK'}</span></div><div style="margin-top:8px"><b>Pick ${item.required_qty} ${esc(p.unit||'units')}</b> · Available ${available}</div>${next?`<div class="small muted">FEFO: take from batch ${esc(next.batch_no)} · expires ${esc(next.expiry_date)} · qty ${next.quantity}</div>`:'<div class="small danger">No unexpired stock available</div>'}</div>${claimText?`<div class="small ${mine?'good':'warn'}" style="padding:7px;margin-top:7px;border-radius:7px"><b>${claimText}</b></div>`:''}${picked?`<button class="pickedDoneBtn full" disabled style="margin-top:9px">PICKED ✓</button><div class="small muted" style="margin-top:6px">Picked ${item.picked_qty} at ${item.picked_at?new Date(item.picked_at).toLocaleString():''}</div>`:profile?.role==='manager'?`<button class="pickListItemBtn primary full" data-id="${item.id}" style="margin-top:9px" ${available<item.required_qty?'disabled':''}>MANAGER FEFO PICK</button>`:claimActive&&!mine?`<button class="full" disabled style="margin-top:9px">IN USE — ${esc(item.claimed_by_name||'ANOTHER USER')}</button>`:`<button class="claimAndScanBtn primary full" data-id="${item.id}" data-name="${esc(p.name||'Ingredient')}" style="margin-top:9px">${mine?'CONTINUE — SCAN BATCH QR':'CLAIM & SCAN BATCH QR'}</button>${mine?`<button class="releaseClaimBtn full" data-id="${item.id}" style="margin-top:6px">RELEASE ITEM</button>`:''}<div class="small muted" style="margin-top:6px">Claiming prevents another picker from working on the same ingredient for 15 minutes.</div>`}</div>`;
}
async function pickListItem(id){if(!confirm('Confirm this ingredient has been physically picked? Stock will be deducted using FEFO.'))return;const {error}=await sb.rpc('pick_recipe_list_item',{p_item_id:id});if(error)return alert(error.message);await showPickLists()}
async function claimAndScan(itemId,name){const {error}=await sb.rpc('claim_pick_list_item',{p_item_id:itemId});if(error)return alert(error.message);await showPickLists(false);await startItemBatchScanner(itemId,name)}
async function releasePickClaim(itemId){const {error}=await sb.rpc('release_pick_list_item',{p_item_id:itemId});if(error)return alert(error.message);await showPickLists(false)}
let itemScanStream=null;let itemScanTimer=null;let itemScanTargetId=null;
async function stopItemBatchScanner(){if(itemScanTimer){clearInterval(itemScanTimer);itemScanTimer=null}if(itemScanStream){itemScanStream.getTracks().forEach(t=>t.stop());itemScanStream=null}$('itemScanVideo').srcObject=null;$('itemScanOverlay').classList.add('hide')}
async function startItemBatchScanner(itemId,name){itemScanTargetId=itemId;$('itemScanTitle').textContent=name+' — scan the batch QR before picking';$('itemScanMsg').textContent='Point the camera at the batch QR label.';$('itemScanOverlay').classList.remove('hide');if(!navigator.mediaDevices?.getUserMedia){$('itemScanMsg').textContent='Camera access is not available in this browser.';return}try{itemScanStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});const video=$('itemScanVideo');video.srcObject=itemScanStream;await video.play();if(!('BarcodeDetector' in window)){$('itemScanMsg').textContent='This browser does not support direct QR scanning. Use Chrome/Android or Safari on a supported iPhone.';return}const detector=new BarcodeDetector({formats:['qr_code']});itemScanTimer=setInterval(async()=>{try{const codes=await detector.detect(video);if(!codes?.length)return;const raw=codes[0].rawValue||'';let batchId=null;try{const u=new URL(raw);batchId=parseInt(u.searchParams.get('batch')||'')}catch{const m=raw.match(/[?&]batch=(\d+)/);if(m)batchId=parseInt(m[1]);else if(/^\d+$/.test(raw.trim()))batchId=parseInt(raw.trim())}if(!batchId)return;clearInterval(itemScanTimer);itemScanTimer=null;$('itemScanMsg').textContent='QR detected. Checking FIFO/FEFO rotation…';await validateScannedBatchForItem(itemScanTargetId,batchId)}catch(e){}},500)}catch(e){$('itemScanMsg').textContent='Camera permission was not granted. Allow camera access and try again.'}}
async function validateScannedBatchForItem(itemId,batchId){const {data:item,error:itemError}=await sb.from('pick_list_items').select('id,product_id,required_qty,picked_qty,status,products(name,unit)').eq('id',itemId).single();if(itemError||!item){await stopItemBatchScanner();return alert('Pick-list item not found.')}const {data:batch,error:batchError}=await sb.from('batches').select('id,product_id,batch_no,received_date,expiry_date,quantity').eq('id',batchId).single();if(batchError||!batch){await stopItemBatchScanner();return alert('Batch QR not recognised.')}if(Number(batch.product_id)!==Number(item.product_id)){$('itemScanMsg').textContent='WRONG PRODUCT — scan the correct ingredient batch QR.';if(itemScanTimer)clearInterval(itemScanTimer);itemScanTimer=setInterval(async()=>{try{const detector=new BarcodeDetector({formats:['qr_code']});const codes=await detector.detect($('itemScanVideo'));if(!codes?.length)return;const u=new URL(codes[0].rawValue);const newBatch=parseInt(u.searchParams.get('batch')||'');if(newBatch&&newBatch!==batchId){clearInterval(itemScanTimer);itemScanTimer=null;await validateScannedBatchForItem(itemId,newBatch)}}catch(e){}},500);return}const remaining=Math.max(0,Number(item.required_qty)-Number(item.picked_qty||0));if(!confirm(`${item.products?.name||'Ingredient'}\n\nBatch: ${batch.batch_no}\nReceived: ${batch.received_date}\nExpiry: ${batch.expiry_date}\nQuantity required now: ${remaining} ${item.products?.unit||'units'}\n\nPress OK to PICK / CONFIRM this scanned batch.`)){await stopItemBatchScanner();return}const {data:result,error}=await sb.rpc('pick_recipe_list_item_by_batch',{p_item_id:itemId,p_batch_id:batchId});await stopItemBatchScanner();if(error){await showPickLists();return alert(error.message)}await showPickLists();if(Number(result?.remaining||0)>0){alert(`Picked ${result.picked_now} from ${result.batch_no}.\n${result.remaining} still required.\nScan the next FIFO/FEFO batch QR.`)}else{alert('PICKED ✓')}}
async function handleBatchQrPick(batchId){const {data:batch,error:batchError}=await sb.from('batches').select('id,product_id,batch_no,expiry_date,received_date,quantity,products(name,scan_code,unit,location)').eq('id',batchId).single();if(batchError||!batch)return alert('Batch QR not recognised.');const {data:items,error:itemError}=await sb.from('pick_list_items').select('id,pick_list_id,required_qty,picked_qty,status,pick_lists!inner(id,status,created_at,cleared_at,recipes(name,code))').eq('product_id',batch.product_id).neq('status','picked').is('pick_lists.cleared_at',null).in('pick_lists.status',['open','in_progress']).order('pick_list_id',{ascending:true}).limit(1);if(itemError)return alert('Could not check the active pick list: '+itemError.message);const item=(items||[])[0];if(!item){history.replaceState({},'',location.pathname);await showPickLists();return alert('This product is not required on an active pick list.')}const p=batch.products||{};const list=item.pick_lists||{};const remaining=Math.max(0,Number(item.required_qty)-Number(item.picked_qty||0));if(!confirm(`RECIPE PICK\n\n${list.recipes?.name||'Recipe'}\n${p.name||p.scan_code}\nBatch: ${batch.batch_no}\nReceived: ${batch.received_date}\nExpiry: ${batch.expiry_date}\nRemaining to pick: ${remaining} ${p.unit||'units'}\n\nPress OK only after taking stock from THIS scanned batch.`)){history.replaceState({},'',location.pathname);await showPickLists();return}const {data:result,error}=await sb.rpc('pick_recipe_list_item_by_batch',{p_item_id:item.id,p_batch_id:batchId});history.replaceState({},'',location.pathname);if(error){await showPickLists();return alert(error.message)}await showPickLists();if(Number(result?.remaining||0)>0){alert(`Picked ${result.picked_now} from batch ${result.batch_no}.\n${result.remaining} still required. Scan the NEXT FEFO/FIFO batch QR.`)}else{alert(`PICKED ✓\n${p.name||p.scan_code} is complete.`)}}