async function printQrLabelIds(ids){
  if(profile?.role!=='manager')return alert('Manager access required.');
  const wanted=new Set(ids.map(Number));
  let rows=qrLabelRowsCache.filter(x=>wanted.has(Number(x.batch_id)));
  if(rows.length!==wanted.size){
    const {data,error}=await sb.from('products').select('id,scan_code,name,category,location,container_type,quantity_per_container,container_measure,batches(id,batch_no,received_date,expiry_date,quantity,supplier)').eq('active',true);
    if(error)return alert(error.message);
    rows=[];
    for(const p of (data||[])){for(const b of (p.batches||[])){if(wanted.has(Number(b.id))){rows.push({batch_id:b.id,scan_code:p.scan_code,name:p.name,category:p.category||'',location:p.location||'',container_type:p.container_type||p.unit||'',quantity_per_container:p.quantity_per_container,container_measure:p.container_measure||'',batch_no:b.batch_no,received_date:b.received_date||'',expiry_date:b.expiry_date||'',quantity:Number(b.quantity||0),supplier:b.supplier||''})}}}
  }
  if(!rows.length)return alert('No batch labels found.');
  const w=window.open('','_blank','width=1000,height=900');
  if(!w)return alert('Allow pop-ups to print QR labels.');
  w.document.write(`<html><head><title>QR Labels</title><style>*{box-sizing:border-box}body{font-family:Arial;margin:0;padding:8px;color:#111;background:#fff}.top{display:flex;justify-content:center;margin-bottom:8px}.labels{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.label{padding:6px;text-align:center;break-inside:avoid;page-break-inside:avoid}.label img{width:220px;height:220px;display:block;margin:0 auto}.caption{width:220px;margin:8px auto 0 auto;line-height:1.15}.name{font-size:20px;font-weight:800;word-wrap:break-word}.pack{font-size:18px;font-weight:700;margin-top:4px;word-wrap:break-word}@media print{button{display:none}body{padding:4mm}.top{display:none}.labels{gap:4mm}.label{padding:0}}</style></head><body><div class="top"><button onclick="print()">PRINT QR CODES</button></div><div id="printLabels" class="labels"></div></body></html>`);
  w.document.close();
  const holder=w.document.getElementById('printLabels');
  for(const x of rows){
    const payloadUrl=new URL(location.origin+location.pathname);
    payloadUrl.searchParams.set('batch',x.batch_id);payloadUrl.searchParams.set('product',x.scan_code||'');payloadUrl.searchParams.set('name',x.name||'');payloadUrl.searchParams.set('batch_no',x.batch_no||'');payloadUrl.searchParams.set('received',x.received_date||'');payloadUrl.searchParams.set('expiry',x.expiry_date||'');payloadUrl.searchParams.set('container',x.container_type||'');if(x.quantity_per_container!==null&&x.quantity_per_container!==undefined)payloadUrl.searchParams.set('container_qty',x.quantity_per_container);payloadUrl.searchParams.set('measure',x.container_measure||'');payloadUrl.searchParams.set('location',x.location||'');payloadUrl.searchParams.set('supplier',x.supplier||'');
    const qr=await makeQrDataUrl(payloadUrl.toString());
    let packText='';
    if(x.quantity_per_container!==null&&x.quantity_per_container!==undefined&&x.quantity_per_container!==''){const qty=String(x.quantity_per_container).replace(/\.0+$/,'').replace(/(\.\d*?)0+$/,'$1');const measure=(x.container_measure||'').trim();const container=(x.container_type||'').trim();packText=[qty,measure,container].filter(Boolean).join(' ')}else{const measure=(x.container_measure||'').trim();const container=(x.container_type||'').trim();packText=[measure,container].filter(Boolean).join(' ')}
    const div=w.document.createElement('div');div.className='label';div.innerHTML=`<img src="${qr}"><div class="caption"><div class="name">${esc(x.name)}</div>${packText?`<div class="pack">${esc(packText)}</div>`:``}</div>`;holder.appendChild(div);
  }
}
async function showUsers(setView=true){if(setView)currentView='users';if(!['manager','qa_manager'].includes(profile?.role))return;let q=sb.from('profiles').select('*').order('created_at');if(profile.role==='qa_manager')q=q.eq('department','QA');const {data,error}=await q;if(error)return alert(error.message);const roleOptions=profile.role==='manager'?`<option value="picker">Picker</option><option value="manager">Manager</option><option value="qa_manager">QA Manager</option><option value="qa">QA</option>`:`<option value="qa">QA</option>`;const intro=profile.role==='qa_manager'?'QA Manager area. You can create QA department staff logins only.':'Manager area. You can create all staff roles, including QA Managers.';$('content').innerHTML=`<div class="card"><h2>Create Staff Account</h2><p class="muted">${intro}</p><div class="grid"><div><label>Username</label><input id="newUsername" placeholder="${profile.role==='qa_manager'?'e.g. qa.jenson':'e.g. sam'}"></div><div><label>Display name</label><input id="newDisplayName" placeholder="${profile.role==='qa_manager'?'e.g. QA Jenson':'e.g. Sam'}"></div><div><label>Password</label><input id="newPassword" type="password" placeholder="Minimum 6 characters"></div><div><label>Role</label><select id="newRole">${roleOptions}</select></div></div><button id="createStaffBtn" class="primary" style="margin-top:10px">CREATE STAFF ACCOUNT</button><p id="createStaffMsg" class="muted"></p></div><div class="card"><h2>${profile.role==='qa_manager'?'QA Department Users':'Users & Roles'}</h2>${(data||[]).map(u=>userAdminRow(u)).join('')||'<p>No users found.</p>'}</div>`;$('createStaffBtn').onclick=createStaffUser}
function userAdminRow(u){if(profile.role==='qa_manager'){return `<div class="row" style="border-top:1px solid #ddd;padding:10px 0"><div style="flex:1"><b>${esc(u.display_name||'QA User')}</b><br><span class="muted">${esc(u.department||'QA')} · ${esc(String(u.role||'').toUpperCase())}</span></div><span class="pill">QA</span></div>`}return `<div class="row" style="border-top:1px solid #ddd;padding:10px 0"><div style="flex:1"><b>${esc(u.display_name||'User')}</b><br><span class="muted">${esc(u.department||'')} ${u.department?'· ':''}${esc(u.user_id)}</span></div><select id="role_${u.user_id}" style="max-width:170px"><option value="picker" ${u.role==='picker'?'selected':''}>Picker</option><option value="manager" ${u.role==='manager'?'selected':''}>Manager</option><option value="qa_manager" ${u.role==='qa_manager'?'selected':''}>QA Manager</option><option value="qa" ${u.role==='qa'?'selected':''}>QA</option></select><button onclick="saveRole('${u.user_id}')">SAVE ROLE</button></div>`}
async function createStaffUser(){const username=$('newUsername').value.trim();const display_name=$('newDisplayName').value.trim()||username;const password=$('newPassword').value;const role=profile.role==='qa_manager'?'qa':$('newRole').value;const msg=$('createStaffMsg');if(!/^[A-Za-z0-9._-]{3,30}$/.test(username)){msg.textContent='Username must be 3–30 characters using letters, numbers, dot, dash or underscore.';return}if(password.length<6){msg.textContent='Password must be at least 6 characters.';return}msg.textContent='Creating account…';const {data,error}=await sb.functions.invoke('create_staff_user',{body:{username,display_name,password,role,department:(role==='qa'||role==='qa_manager')?'QA':null}});if(error){msg.textContent=error.message||'Could not create staff account.';return}if(data?.error){msg.textContent=data.error;return}msg.textContent=`${display_name} created as ${String(data.role||role).toUpperCase()} (username: ${username}).`;setTimeout(showUsers,600)}
async function saveRole(id){if(profile?.role!=='manager')return alert('Only the main Manager can change staff roles.');const role=$('role_'+id).value;const {error}=await sb.rpc('set_user_role',{p_user_id:id,p_role:role});if(error)return alert(error.message);alert('Role updated.');showUsers()}
$('itemScanCancel').onclick=stopItemBatchScanner;$('signin').onclick=signIn;$('claimManager').onclick=claimManager;$('stockBtn').onclick=()=>showStock();$('expiryBtn').onclick=showExpiry;$('historyBtn').onclick=showHistory;$('recipesBtn').onclick=showRecipes;$('pickListsBtn').onclick=showPickLists;$('concessionsBtn').onclick=showConcessions;$('receiveBtn').onclick=showReceive;$('qrLabelsBtn').onclick=showQrLabels;$('usersBtn').onclick=showUsers;$('searchBtn').onclick=showStock;$('search').addEventListener('keydown',e=>{if(e.key==='Enter')showStock()});$('logout').onclick=async()=>{if(realtime)await sb.removeChannel(realtime);await sb.auth.signOut();location.reload()};
boot();
let deferredInstallPrompt=null;
window.addEventListener('beforeinstallprompt',(e)=>{e.preventDefault();deferredInstallPrompt=e;const b=$('installbtn');if(b)b.classList.remove('hide')});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;const b=$('installbtn');if(b)b.classList.add('hide')});
async function installFoodApp(){if(!deferredInstallPrompt){alert('Use your browser menu and choose Add to Home screen / Install app.');return}deferredInstallPrompt.prompt();try{await deferredInstallPrompt.userChoice}catch(_){}deferredInstallPrompt=null;const b=$('installbtn');if(b)b.classList.add('hide')}
if($('installbtn'))$('installbtn').onclick=installFoodApp;
if('serviceWorker' in navigator){window.addEventListener('load',()=>{navigator.serviceWorker.register('/service-worker.js').catch(()=>{})})}