async function qaDecision(id,decision){
  if(profile?.role!=='qa')return alert('QA access required.');
  const label=decision==='USE'?'ALLOW USE UNDER CONCESSION':'AUTHORISE THROW AWAY';
  const comment=(prompt(`QA decision: ${label}\n\nEnter QA comment / conditions:`, decision==='USE'?'Approved for use under concession':'Approved for disposal')||'').trim();
  if(!comment)return alert('QA comment is required.');
  if(!confirm(`${label} for ${concessionNo(id)}?\n\nThis decision will be recorded against your QA login.`))return;
  const {error}=await sb.rpc('qa_decide_concession',{p_concession_id:id,p_decision:decision,p_comment:comment});
  if(error)return alert(error.message);
  alert(decision==='USE'?'QA concession approved for USE. Stock has NOT been deducted.':'QA approved THROW AWAY. The concession quantity has now been deducted from stock.');
  await showConcessions();
}
async function printConcession(id){
  const {data:c,error}=await sb.from('concessions').select('*,products(name,scan_code,unit,container_type,quantity_per_container,container_measure),batches(batch_no,received_date,expiry_date,quantity,supplier)').eq('id',id).single();
  if(error)return alert(error.message);
  let requestedBy='',qaBy='';
  if(c.requested_by){const r=await sb.from('profiles').select('display_name').eq('user_id',c.requested_by).maybeSingle();requestedBy=r.data?.display_name||''}
  if(c.qa_by){const q=await sb.from('profiles').select('display_name').eq('user_id',c.qa_by).maybeSingle();qaBy=q.data?.display_name||''}
  const p=c.products||{},b=c.batches||{};
  const decision=c.status==='APPROVED_USE'?'USE UNDER CONCESSION':c.status==='APPROVED_THROW_AWAY'?'THROW AWAY / DISPOSE':'PENDING QA DECISION';
  const w=window.open('','_blank','width=850,height=1000');if(!w)return alert('Allow pop-ups to print the concession sheet.');
  w.document.write(`<html><head><title>${concessionNo(c.id)}</title><style>body{font-family:Arial;padding:28px;color:#111}h1{text-align:center;margin:0 0 4px}.sub{text-align:center;margin-bottom:22px}table{width:100%;border-collapse:collapse;margin:14px 0}th,td{border:1px solid #222;padding:10px;text-align:left;vertical-align:top}th{width:28%;background:#eee}.decision{font-size:22px;font-weight:800;text-align:center;border:2px solid #111;padding:14px;margin:18px 0}.sign{height:70px}.note{font-size:12px}@media print{button{display:none}body{padding:10mm}}</style></head><body><button onclick="print()">PRINT CONCESSION SHEET</button><h1>FOOD STOCK CONTROL</h1><div class="sub"><b>QA CONCESSION / DISPOSITION RECORD</b><br>${concessionNo(c.id)}</div><table><tr><th>Product</th><td>${esc(p.name||'')}</td></tr><tr><th>Product code</th><td>${esc(p.scan_code||'')}</td></tr><tr><th>Batch / Lot</th><td>${esc(b.batch_no||'')}</td></tr><tr><th>Quantity affected</th><td>${c.quantity} ${esc(p.unit||'')}</td></tr><tr><th>Received date</th><td>${esc(b.received_date||'')}</td></tr><tr><th>Expiry date</th><td>${esc(b.expiry_date||'')}</td></tr><tr><th>Supplier</th><td>${esc(b.supplier||'')}</td></tr><tr><th>Reason for concession</th><td>${esc(c.reason||'')}</td></tr><tr><th>Raised by</th><td>${esc(requestedBy)}</td></tr><tr><th>Raised at</th><td>${new Date(c.requested_at).toLocaleString()}</td></tr></table><div class="decision">${esc(decision)}</div><table><tr><th>QA name</th><td>${esc(qaBy)}</td></tr><tr><th>QA comments / conditions</th><td>${esc(c.qa_comment||'')}</td></tr><tr><th>Decision date/time</th><td>${c.decided_at?new Date(c.decided_at).toLocaleString():''}</td></tr><tr><th>QA signature</th><td class="sign"></td></tr></table><p class="note">This form records the QA disposition of affected stock. Product may only be used under concession when authorised by a QA login. Throw-away quantities are deducted from stock only after QA authorisation.</p></body></html>`);
  w.document.close();
}
let qrLabelRowsCache=[];
async function showQrLabels(setView=true){if(setView)currentView='qrlabels';if(profile?.role!=='manager')return alert('Manager access required.');const {data,error}=await sb.from('products').select('id,scan_code,name,category,location,active,container_type,quantity_per_container,container_measure,batches(id,batch_no,received_date,expiry_date,quantity,supplier)').eq('active',true).order('scan_code');if(error)return alert(error.message);const rows=[];for(const p of (data||[])){for(const b of (p.batches||[])){if(Number(b.quantity)>0){rows.push({batch_id:b.id,product_id:p.id,scan_code:p.scan_code,name:p.name,category:p.category||'',location:p.location||'',container_type:p.container_type||p.unit||'',quantity_per_container:p.quantity_per_container,container_measure:p.container_measure||'',batch_no:b.batch_no,received_date:b.received_date||'',expiry_date:b.expiry_date||'',quantity:Number(b.quantity||0),supplier:b.supplier||''})}}}rows.sort((a,b)=>String(a.name).localeCompare(String(b.name))||String(a.received_date).localeCompare(String(b.received_date))||Number(a.batch_id)-Number(b.batch_id));qrLabelRowsCache=rows;$('content').innerHTML=`<div class="card"><h2>QR LABELS</h2><p class="muted">Manager-only batch label area. Each QR identifies one physical stock batch so the Picker can scan it and the system can enforce FIFO / FEFO rotation.</p></div><div class="toolbarSticky"><input id="qrLabelSearch" placeholder="Search product, code, batch, supplier or location"><div class="row" style="margin-top:8px"><button id="qrSelectAllBtn">SELECT ALL SHOWN</button><button id="qrClearSelectionBtn">CLEAR SELECTION</button><button id="qrPrintSelectedBtn" class="primary">PRINT SELECTED</button><button id="qrPrintAllBtn" class="primary">PRINT ALL ACTIVE BATCH QR LABELS</button></div><p id="qrLabelCount" class="small muted"></p></div><div id="qrLabelList"></div>`;$('qrLabelSearch').oninput=renderQrLabelRows;$('qrSelectAllBtn').onclick=()=>document.querySelectorAll('.qrBatchCheck').forEach(c=>c.checked=true);$('qrClearSelectionBtn').onclick=()=>document.querySelectorAll('.qrBatchCheck').forEach(c=>c.checked=false);$('qrPrintSelectedBtn').onclick=()=>printSelectedQrLabels(false);$('qrPrintAllBtn').onclick=()=>printSelectedQrLabels(true);renderQrLabelRows()}
function renderQrLabelRows(){const q=($('qrLabelSearch')?.value||'').trim().toLowerCase();const rows=qrLabelRowsCache.filter(x=>{if(!q)return true;return [x.scan_code,x.name,x.category,x.location,x.batch_no,x.supplier,x.received_date,x.expiry_date,x.container_type,x.quantity_per_container,x.container_measure].some(v=>String(v||'').toLowerCase().includes(q))});$('qrLabelCount').textContent=`${rows.length} active batch label${rows.length===1?'':'s'} shown`;$('qrLabelList').innerHTML=rows.length?rows.map(x=>`<div class="card qrLabelRow"><div class="row"><input class="qrBatchCheck" type="checkbox" value="${x.batch_id}"><div style="flex:1;min-width:220px"><b>${esc(x.name)}</b><br><span class="muted">${esc(x.scan_code)} · ${esc(x.category)} · ${esc(x.location)}</span></div><button onclick="printQrLabelIds([${x.batch_id}])">PRINT QR</button></div><div style="margin-top:8px"><b>Batch:</b> ${esc(x.batch_no)} · <b>Received:</b> ${esc(x.received_date)} · <b>Expiry:</b> ${esc(x.expiry_date)} · <b>Qty:</b> ${x.quantity}${x.supplier?` · <b>Supplier:</b> ${esc(x.supplier)}`:''}</div><div class="grid" style="margin-top:10px"><div><label>Container type</label><input id="ct_${x.product_id}_${x.batch_id}" value="${esc(x.container_type||'')}" placeholder="box / pack / bottle / carton"></div><div><label>Quantity per container</label><input id="cq_${x.product_id}_${x.batch_id}" type="number" step="0.01" min="0" value="${x.quantity_per_container??''}" placeholder="e.g. 12 or 2"></div><div><label>Measure</label><input id="cm_${x.product_id}_${x.batch_id}" value="${esc(x.container_measure||'')}" placeholder="each / litre / kg / g"></div></div><button style="margin-top:8px" onclick="savePackagingInfo(${x.product_id},${x.batch_id})">SAVE PACK / CONTAINER INFO</button></div>`).join(''):'<div class="card">No active stock batches match your search.</div>'}
async function savePackagingInfo(productId,batchId){if(profile?.role!=='manager')return alert('Manager access required.');const ct=$('ct_'+productId+'_'+batchId)?.value.trim()||null;const qRaw=$('cq_'+productId+'_'+batchId)?.value;const cq=qRaw===''?null:Number(qRaw);const cm=$('cm_'+productId+'_'+batchId)?.value.trim()||null;const {error}=await sb.from('products').update({container_type:ct,quantity_per_container:Number.isFinite(cq)?cq:null,container_measure:cm}).eq('id',productId);if(error)return alert(error.message);alert('Pack / container information saved.');await showQrLabels()}
async function makeQrDataUrl(text){const holder=document.createElement('div');holder.style.position='fixed';holder.style.left='-9999px';holder.style.top='-9999px';document.body.appendChild(holder);new QRCode(holder,{text,width:420,height:420,correctLevel:QRCode.CorrectLevel.M});await new Promise(r=>setTimeout(r,70));const canvas=holder.querySelector('canvas');const img=holder.querySelector('img');const dataUrl=canvas?canvas.toDataURL('image/png'):(img?img.src:'');holder.remove();return dataUrl}
async function printSelectedQrLabels(printAll){let ids;if(printAll){ids=qrLabelRowsCache.map(x=>x.batch_id)}else{ids=[...document.querySelectorAll('.qrBatchCheck:checked')].map(x=>parseInt(x.value))}if(!ids.length)return alert('Select at least one batch label to print.');await printQrLabelIds(ids)}